[build-system]
requires = ["setuptools>=70.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "raef"
version = "0.1.0"
description = "Retrieval-Augmented Extended Forecasting"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "Apache-2.0" }
authors = [
  { name="Juan Pablo Villa Serna", email="juan.pablo.villa@fau.de" }
]

# required dependencies
dependencies = [
  "numpy>=1.26.4",
  "pandas>=2.1.4",
  "requests>=2.32.3",
  "torch==2.8.0.dev20250315+cu128",
  "torchaudio==2.6.0.dev20250315+cu128",
  "torchmetrics==1.6.1",
  "torchvision==0.22.0.dev20250315+cu128",
]

# optional dependencies (install via: pip install yourpkg[dev])
[project.optional-dependencies]
dev = [
  "pytest",
  "black",
  "mypy",
]
gpu = [
  "torch",
  "faiss-gpu"
]

[tool.setuptools]
license-files = ["LICENSE"]

# Ensure setuptools finds your package inside src/
[tool.setuptools.packages.find]
where = ["src"]
